"""Add employee management fields to User model

Revision ID: c279853f7c0e
Revises: 
Create Date: 2025-06-21 08:32:55.518165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c279853f7c0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('employment_type', sa.String(length=50), nullable=True, server_default='full_time'))
    op.add_column('users', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('hourly_rate', sa.Integer(), nullable=True, server_default='1000'))
    op.add_column('users', sa.Column('monthly_salary', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('payment_method', sa.String(length=50), nullable=True, server_default='bank_transfer'))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('emergency_contact', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('emergency_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['employee_id'])
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    
    # 既存のユーザーにデフォルト値を設定
    op.execute("UPDATE users SET hourly_rate = 1000 WHERE hourly_rate IS NULL")
    op.execute("UPDATE users SET employment_type = 'full_time' WHERE employment_type IS NULL")
    op.execute("UPDATE users SET payment_method = 'bank_transfer' WHERE payment_method IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'address')
    op.drop_column('users', 'emergency_phone')
    op.drop_column('users', 'emergency_contact')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'payment_method')
    op.drop_column('users', 'monthly_salary')
    op.drop_column('users', 'hourly_rate')
    op.drop_column('users', 'hire_date')
    op.drop_column('users', 'employment_type')
    op.drop_column('users', 'position')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###