"""Add insurance and income tax rate tables

Revision ID: e780b3e72707
Revises: f2fa835e85f4
Create Date: 2025-06-21 13:09:35.340207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e780b3e72707'
down_revision = 'f2fa835e85f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_settings', sa.Column('use_db_rates', sa.Boolean(), nullable=True))
    op.add_column('payroll_settings', sa.Column('default_prefecture', sa.String(length=50), nullable=True))
    op.add_column('payroll_settings', sa.Column('default_industry', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_settings', 'default_industry')
    op.drop_column('payroll_settings', 'default_prefecture')
    op.drop_column('payroll_settings', 'use_db_rates')
    # ### end Alembic commands ###