"""Add Payslip and PayslipDetail models

Revision ID: f2fa835e85f4
Revises: rename_employee_id_to_code
Create Date: 2025-06-21 12:41:07.572279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fa835e85f4'
down_revision = 'rename_employee_id_to_code'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###